openapi: "3.0.0"

info:
  title: Ecommernce API
  description:  Ecommernce API
  version: "0.1"

tags:
  - name: Users
    description: User Description

paths:
  /users:
    get:
      tags:
        - Users
      summary: Get all market streams, or only those for a specific stream.
      operationId: getAllUsers
      description: Returns either all available market type stream relations, or only those for chosen stream.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDto'

components:
  schemas:
    UserDto:
      type: object
      description: UserDto
      required:
        - marketUpdates
      properties:
        id:
          type: integer
          format: int64
          description: The id of the event
        name:
          type: string
          description: The name of the event
        email:
          type: string
          description: The name of the event
        address:
          type: string
          description: The name of the event