openapi: "3.0.0"

info:
  title: Ecommernce API
  description:  Ecommernce API
  version: "0.1"

tags:
  - name: Users
    description: User Description

paths:
  ###########################################################################################
  # Users
  ###########################################################################################
  /users:
    get:
      tags:
        - Users
      summary: Get all market streams, or only those for a specific stream.
      operationId: getAllUsers
      description: Returns either all available market type stream relations, or only those for chosen stream.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDto'
  /users/{id}:
    get:
      tags:
        - Users
      summary: Get a user by its id
      operationId: getUser
      description: Get a user by its id
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the user
          schema:
            type: integer
            format: int64
        - in: query
          name: myRequestParam
          required: false
          description: The id of the sport to return
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
    put:
      tags:
        - Users
      summary: Update a user by its id
      operationId: updateUser
      description: Update a user by its id
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the user
          schema:
            type: integer
            format: int64
      requestBody:
        description: User details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
    delete:
      tags:
        - Users
      summary: Delete user by id
      operationId: deleteUser
      description:  Delete user by id
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the user
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
  /users/register:
    post:
      tags:
        - Users
      summary: Register a new user
      operationId: registerUser
      description: Registers a new user
      requestBody:
        description: User registration details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationDto'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
  /users/login:
    post:
      tags:
        - Users
      summary: Login an existing user
      operationId: loginUser
      description: Login an existing user
#      parameters:
#        - in: path
#          name: email
#          required: false
#          description: The email of the user
#          schema:
#            type: string
#        - in: path
#          name: password
#          required: false
#          description: The password of the user
#          schema:
#            type: string
      requestBody:
        description: User login details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginDto'
      responses:
        '200':
          description: User logged successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'

  ###########################################################################################
  # Package
  ###########################################################################################

components:
  schemas:
    UserDto:
      type: object
      description: UserDto
      required:
        - marketUpdates
      properties:
        id:
          type: integer
          format: int64
          description: The id of the event
        name:
          type: string
          description: The name of the event
        email:
          type: string
          description: The name of the event
        address:
          type: string
          description: The name of the event
    UserRegistrationDto:
      type: object
      properties:
        name:
          type: string
          description: The name of the user
        email:
          type: string
          description: The email address of the user
        address:
          type: string
          description: The address of the user
        password:
          type: string
          description: The password of the user
      required:
        - name
        - email
        - address
        - password
    UserLoginDto:
      type: object
      properties:
        email:
          type: string
          description: The email of the user
        password:
          type: string
          description: The password of the user
      required:
        - email
        - password